name: Docker Build with Buildx

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # checks out the repository
    - name: Checkout code
      uses: actions/checkout@v4

    # sets up docker buildx with a custom container image
    - id: setup-docker
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        driver-opts: |
          image=000000000000.dkr.ecr.eu-west-1.amazonaws.com/moby/buildkit:buildx-stable-1

    # login to AWS ECR
    - name: Log in to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1
      with:
        region: eu-west-1

    # build and push the container image
    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: 000000000000.dkr.ecr.eu-west-1.amazonaws.com/my-repository:latest

    # Optional: clean up docker resources
    - name: Clean up
      run: |
        docker system prune -af
